import type { FullQuestionRecord } from "@/lib/types/full-question-record";

/**
 * 16 real questions transcribed verbatim (text/choices/explanations
 * unedited) from
 * pilot-question-bank/data/easa/atpl-a/air-law/en/original_syllabus_aligned_batch1.jsonl,
 * spanning 15 distinct chapters. Each `questionId` is traceable back to its
 * original bank record. This is real, already-reviewed EASA ATPL(A) Air Law
 * content (provenance: original_syllabus_aligned, status: active,
 * verified: true in the bank) — not invented for this app.
 */
export const easaAtplAirLawQuestions: readonly FullQuestionRecord[] = [
  {
    questionId: "EASA-ATPLA-AL-000001",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Abbreviations and Definitions",
    learningObjective: "Abbreviations and Definitions",
    questionType: "single_choice",
    questionText: "What does AIP mean?",
    choices: [
      { label: "A", text: "Aeronautical Information Publication." },
      { label: "B", text: "Aircraft Inspection Programme." },
      { label: "C", text: "Air Information Procedures." },
      { label: "D", text: "Airport Information Panel." },
    ],
    correctAnswer: "A",
    explanation: "Aeronautical Information Publication.",
    incorrectAnswerExplanations: {
      B: "Not correct: Aircraft Inspection Programme.",
      C: "Not correct: Air Information Procedures.",
      D: "Not correct: Airport Information Panel.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, Article 2 (definitions), Appendix 1, and SERA terminology",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for SERA, August 2025 revision",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-standardised-european-rules-air",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000003",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Abbreviations and Definitions",
    learningObjective: "Abbreviations and Definitions",
    questionType: "single_choice",
    questionText: "What does FIR mean?",
    choices: [
      { label: "A", text: "Flight instrument rating." },
      { label: "B", text: "Final instrument reading." },
      { label: "C", text: "Flight information region." },
      { label: "D", text: "Flight information report." },
    ],
    correctAnswer: "C",
    explanation: "Flight information region.",
    incorrectAnswerExplanations: {
      A: "Not correct: Flight instrument rating.",
      B: "Not correct: Final instrument reading.",
      D: "Not correct: Flight information report.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, Article 2 (definitions), Appendix 1, and SERA terminology",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for SERA, August 2025 revision",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-standardised-european-rules-air",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000016",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "International Aviation Law and the Chicago Convention",
    learningObjective: "International Aviation Law and the Chicago Convention",
    questionType: "single_choice",
    questionText: "What must a State do when it cannot comply fully with an ICAO Standard?",
    choices: [
      { label: "A", text: "Immediately cease all international operations until compliant." },
      { label: "B", text: "Seek approval from IATA before continuing operations." },
      { label: "C", text: "Nothing; differences do not need to be reported to ICAO." },
      {
        label: "D",
        text: "Notify ICAO of the difference under the Convention's difference-notification process.",
      },
    ],
    correctAnswer: "D",
    explanation:
      "Notify ICAO of the difference under the Convention's difference-notification process.",
    incorrectAnswerExplanations: {
      A: "Not correct: Immediately cease all international operations until compliant.",
      B: "Not correct: Seek approval from IATA before continuing operations.",
      C: "Not correct: Nothing; differences do not need to be reported to ICAO.",
    },
    regulationReference:
      "Chicago Convention, Articles 1, 5, 6, 7, 37, 38, 43, 48 and 50; International Air Services Transit Agreement",
    difficulty: "intermediate",
    sourceTitle: "Convention on International Civil Aviation (Chicago Convention), 9th edition",
    sourceUrl: "https://www.icao.int/publications/pages/doc7300.aspx",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000019",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "International Aviation Law and the Chicago Convention",
    learningObjective: "International Aviation Law and the Chicago Convention",
    questionType: "single_choice",
    questionText: "What does the first freedom of the air permit?",
    choices: [
      { label: "A", text: "Landing in another State for non-traffic purposes." },
      { label: "B", text: "Picking up passengers in another State bound for the home State." },
      {
        label: "C",
        text: "Overflight of another State without landing, subject to applicable permission or agreement.",
      },
      { label: "D", text: "Carrying passengers between two points within a single foreign State." },
    ],
    correctAnswer: "C",
    explanation:
      "Overflight of another State without landing, subject to applicable permission or agreement.",
    incorrectAnswerExplanations: {
      A: "That is the second freedom, not the first.",
      B: "That describes cabotage-like traffic rights, not the first freedom.",
      D: "That describes a form of cabotage, not an overflight freedom.",
    },
    regulationReference:
      "Chicago Convention, Articles 1, 5, 6, 7, 37, 38, 43, 48 and 50; International Air Services Transit Agreement",
    difficulty: "intermediate",
    sourceTitle: "Convention on International Civil Aviation (Chicago Convention), 9th edition",
    sourceUrl: "https://www.icao.int/publications/pages/doc7300.aspx",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000041",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Aircraft Registration and Markings",
    learningObjective: "Aircraft Registration and Markings",
    questionType: "single_choice",
    questionText: "What is the purpose of an aircraft certificate of registration?",
    choices: [
      { label: "A", text: "To confirm the aircraft's airworthiness for flight." },
      { label: "B", text: "To record the pilot in command's licence details." },
      { label: "C", text: "To authorise the aircraft to carry passengers commercially." },
      {
        label: "D",
        text: "To record the aircraft's nationality and registration in the responsible State's register.",
      },
    ],
    correctAnswer: "D",
    explanation:
      "To record the aircraft's nationality and registration in the responsible State's register. Note: Check the applicable State AIP and national differences before operational use.",
    incorrectAnswerExplanations: {
      A: "Not correct: To confirm the aircraft's airworthiness for flight.",
      B: "Not correct: To record the pilot in command's licence details.",
      C: "Not correct: To authorise the aircraft to carry passengers commercially.",
    },
    regulationReference: "Chicago Convention, Articles 17-21; ICAO Annex 7; applicable State registration law",
    difficulty: "intermediate",
    sourceTitle: "Chicago Convention aircraft nationality framework",
    sourceUrl: "https://www.icao.int/publications/pages/doc7300.aspx",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000051",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Airworthiness of Aircraft",
    learningObjective: "Airworthiness of Aircraft",
    questionType: "single_choice",
    questionText: "What does a certificate of airworthiness signify?",
    choices: [
      {
        label: "A",
        text: "That the aircraft conforms to its approved design and is considered airworthy under the applicable requirements.",
      },
      { label: "B", text: "That the aircraft is authorised for commercial passenger flights." },
      { label: "C", text: "That the pilot flying it holds an appropriate licence." },
      { label: "D", text: "That the aircraft has been recently refuelled and inspected before this flight." },
    ],
    correctAnswer: "A",
    explanation:
      "That the aircraft conforms to its approved design and is considered airworthy under the applicable requirements.",
    incorrectAnswerExplanations: {
      B: "Not correct: That the aircraft is authorised for commercial passenger flights.",
      C: "Not correct: That the pilot flying it holds an appropriate licence.",
      D: "Not correct: That the aircraft has been recently refuelled and inspected before this flight.",
    },
    regulationReference:
      "Regulations (EU) No 748/2012 and No 1321/2014, as amended; Regulation (EU) 2018/1139, Article 3 definitions",
    difficulty: "intermediate",
    sourceTitle: "EASA Initial and Continuing Airworthiness rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-continuing-airworthiness",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000081",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Altimeter Setting Procedures",
    learningObjective: "Altimeter Setting Procedures",
    questionType: "single_choice",
    questionText: "What does QNH make an altimeter indicate on the ground?",
    choices: [
      { label: "A", text: "Height above the runway threshold." },
      { label: "B", text: "Zero, regardless of elevation." },
      { label: "C", text: "Pressure altitude referenced to standard datum." },
      {
        label: "D",
        text: "Aerodrome elevation above mean sea level, within instrument and pressure tolerances.",
      },
    ],
    correctAnswer: "D",
    explanation:
      "Aerodrome elevation above mean sea level, within instrument and pressure tolerances. Note: Check the applicable State AIP and national differences before operational use.",
    incorrectAnswerExplanations: {
      A: "That describes height above a local reference, not aerodrome elevation above MSL.",
      B: "QNH does not read zero at the aerodrome; that is QFE's behaviour.",
      C: "That describes pressure altitude referenced to standard pressure, not QNH.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, SERA.8015 and Article 2 definitions; State AIP altimeter-setting procedures",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for SERA, August 2025 revision",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-standardised-european-rules-air",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000082",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Altimeter Setting Procedures",
    learningObjective: "Altimeter Setting Procedures",
    questionType: "single_choice",
    questionText: "What does QFE make an altimeter indicate at its reference datum?",
    choices: [
      { label: "A", text: "Aerodrome elevation above mean sea level." },
      { label: "B", text: "The current flight level." },
      { label: "C", text: "Density altitude at the reference datum." },
      { label: "D", text: "Approximately zero." },
    ],
    correctAnswer: "D",
    explanation:
      "Approximately zero. Note: Check the applicable State AIP and national differences before operational use.",
    incorrectAnswerExplanations: {
      A: "That is the effect of QNH, not QFE.",
      B: "Flight level is unrelated to a local QFE reading.",
      C: "Density altitude is a different, temperature-corrected concept.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, SERA.8015 and Article 2 definitions; State AIP altimeter-setting procedures",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for SERA, August 2025 revision",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-standardised-european-rules-air",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000101",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Aeronautical Information Service",
    learningObjective: "Aeronautical Information Service",
    questionType: "single_choice",
    questionText: "What is the purpose of aeronautical information services?",
    choices: [
      { label: "A", text: "To operate air traffic control services directly." },
      { label: "B", text: "To issue pilot medical certificates." },
      { label: "C", text: "To enforce customs and immigration requirements at aerodromes." },
      {
        label: "D",
        text: "To provide aeronautical data and information necessary for safe, orderly, and efficient air navigation.",
      },
    ],
    correctAnswer: "D",
    explanation:
      "To provide aeronautical data and information necessary for safe, orderly, and efficient air navigation.",
    incorrectAnswerExplanations: {
      A: "Not correct: To operate air traffic control services directly.",
      B: "Not correct: To issue pilot medical certificates.",
      C: "Not correct: To enforce customs and immigration requirements at aerodromes.",
    },
    regulationReference: "Regulation (EU) 2017/373, Annex VI (Part-AIS), including AIS.OR requirements",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for ATM/ANS",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000111",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Air Traffic Services and Airspace",
    learningObjective: "Air Traffic Services and Airspace",
    questionType: "single_choice",
    questionText: "What are the three principal air traffic services?",
    choices: [
      { label: "A", text: "Air traffic control service, radar service, and weather service." },
      { label: "B", text: "Flight information service, customs service, and alerting service." },
      { label: "C", text: "Air traffic control service, flight information service, and alerting service." },
      { label: "D", text: "Air traffic control service, search and rescue service, and airport service." },
    ],
    correctAnswer: "C",
    explanation: "Air traffic control service, flight information service, and alerting service.",
    incorrectAnswerExplanations: {
      A: "Not correct: Air traffic control service, radar service, and weather service.",
      B: "Not correct: Flight information service, customs service, and alerting service.",
      D: "Not correct: Air traffic control service, search and rescue service, and airport service.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, Article 2 and SERA.6001; Regulation (EU) 2017/373, Annex IV (Part-ATS)",
    difficulty: "intermediate",
    sourceTitle: "EASA SERA and ATM/ANS rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000121",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Air Traffic Control Services",
    learningObjective: "Air Traffic Control Services",
    questionType: "single_choice",
    questionText: "What is the purpose of air traffic control service?",
    choices: [
      { label: "A", text: "To generate revenue for the air navigation service provider." },
      { label: "B", text: "To prevent collisions and expedite and maintain an orderly flow of air traffic." },
      { label: "C", text: "To enforce customs and immigration compliance." },
      { label: "D", text: "To provide weather forecasting exclusively." },
    ],
    correctAnswer: "B",
    explanation: "To prevent collisions and expedite and maintain an orderly flow of air traffic.",
    incorrectAnswerExplanations: {
      A: "Not correct: To generate revenue for the air navigation service provider.",
      C: "Not correct: To enforce customs and immigration compliance.",
      D: "Not correct: To provide weather forecasting exclusively.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, Sections 8, 11 and 14; Regulation (EU) 2017/373, Annex IV (Part-ATS)",
    difficulty: "intermediate",
    sourceTitle: "EASA SERA and ATM/ANS rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000141",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Aerodrome Control Service",
    learningObjective: "Aerodrome Control Service",
    questionType: "single_choice",
    questionText: "What traffic is managed by an aerodrome control tower?",
    choices: [
      {
        label: "A",
        text: "Aircraft and vehicles on the manoeuvring area and aircraft in the aerodrome circuit or vicinity within its responsibility.",
      },
      { label: "B", text: "All aircraft anywhere within the entire FIR." },
      { label: "C", text: "Only aircraft on final approach beyond 10 nautical miles." },
      { label: "D", text: "Only aircraft operating under IFR." },
    ],
    correctAnswer: "A",
    explanation:
      "Aircraft and vehicles on the manoeuvring area and aircraft in the aerodrome circuit or vicinity within its responsibility.",
    incorrectAnswerExplanations: {
      B: "Not correct: All aircraft anywhere within the entire FIR.",
      C: "Not correct: Only aircraft on final approach beyond 10 nautical miles.",
      D: "Not correct: Only aircraft operating under IFR.",
    },
    regulationReference:
      "Regulation (EU) No 923/2012, SERA.3210, SERA.8005 and Section 12; Regulation (EU) 2017/373, Annex IV",
    difficulty: "intermediate",
    sourceTitle: "EASA SERA and ATM/ANS rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000161",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Area Control Service",
    learningObjective: "Area Control Service",
    questionType: "single_choice",
    questionText: "What traffic is principally served by an area control centre?",
    choices: [
      { label: "A", text: "Aircraft operating only within an aerodrome traffic circuit." },
      { label: "B", text: "Aircraft parked on the ground awaiting departure." },
      { label: "C", text: "Only VFR flights below 3000 ft." },
      { label: "D", text: "Controlled flights in control areas, mainly during the en-route phase." },
    ],
    correctAnswer: "D",
    explanation: "Controlled flights in control areas, mainly during the en-route phase.",
    incorrectAnswerExplanations: {
      A: "Not correct: Aircraft operating only within an aerodrome traffic circuit.",
      B: "Not correct: Aircraft parked on the ground awaiting departure.",
      C: "Not correct: Only VFR flights below 3000 ft.",
    },
    regulationReference:
      "Regulation (EU) 2017/373, Annex IV (Part-ATS); applicable separation minima and State procedures",
    difficulty: "intermediate",
    sourceTitle: "EASA ATM/ANS rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000181",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Radar and Surveillance in Air Traffic Control",
    learningObjective: "Radar and Surveillance in Air Traffic Control",
    questionType: "single_choice",
    questionText: "What is primary surveillance radar?",
    choices: [
      { label: "A", text: "A system requiring a functioning transponder reply." },
      {
        label: "B",
        text: "A system that detects targets from reflected radio energy without requiring an aircraft transponder.",
      },
      { label: "C", text: "A system that only detects aircraft altitude, not position." },
      { label: "D", text: "A ground-based visual observation system." },
    ],
    correctAnswer: "B",
    explanation:
      "A system that detects targets from reflected radio energy without requiring an aircraft transponder.",
    incorrectAnswerExplanations: {
      A: "Not correct: A system requiring a functioning transponder reply.",
      C: "Not correct: A system that only detects aircraft altitude, not position.",
      D: "Not correct: A ground-based visual observation system.",
    },
    regulationReference: "Regulation (EU) No 923/2012, Section 13; Regulation (EU) 2017/373, Annex IV (Part-ATS)",
    difficulty: "intermediate",
    sourceTitle: "EASA SERA and ATM/ANS surveillance rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000194",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Secondary Surveillance Radar",
    learningObjective: "Secondary Surveillance Radar",
    questionType: "single_choice",
    questionText: "Which transponder code indicates a general emergency?",
    choices: [
      { label: "A", text: "7600." },
      { label: "B", text: "7500." },
      { label: "C", text: "7700." },
      { label: "D", text: "1200." },
    ],
    correctAnswer: "C",
    explanation: "7700.",
    incorrectAnswerExplanations: {
      A: "7600 is the radio-failure code, not the general emergency code.",
      B: "7500 indicates unlawful interference, not a general emergency.",
      D: "1200 is a VFR conspicuity code in some jurisdictions, not an emergency code.",
    },
    regulationReference: "Regulation (EU) No 923/2012, SERA.13001-SERA.13020",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for SERA, August 2025 revision",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-standardised-european-rules-air",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000202",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Alerting Service",
    learningObjective: "Alerting Service",
    questionType: "single_choice",
    questionText: "What is INCERFA?",
    choices: [
      { label: "A", text: "The alert phase." },
      { label: "B", text: "The uncertainty phase." },
      { label: "C", text: "The distress phase." },
      { label: "D", text: "A routine flight-plan update." },
    ],
    correctAnswer: "B",
    explanation: "The uncertainty phase.",
    incorrectAnswerExplanations: {
      A: "ALERFA is the alert phase, one stage beyond uncertainty.",
      C: "DETRESFA is the distress phase, the most serious stage.",
      D: "INCERFA is triggered by uncertainty itself, not a routine update.",
    },
    regulationReference: "Regulation (EU) No 923/2012, SERA.10001-SERA.10005; Regulation (EU) 2017/373, Annex IV",
    difficulty: "intermediate",
    sourceTitle: "EASA SERA and ATM/ANS alerting-service rules",
    sourceUrl:
      "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-air-traffic-managementair-navigation-services-provision-services",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000221",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Aerodromes",
    learningObjective: "Aerodromes",
    questionType: "single_choice",
    questionText: "What is an aerodrome?",
    choices: [
      {
        label: "A",
        text: "A defined area intended wholly or partly for aircraft arrival, departure, and surface movement.",
      },
      { label: "B", text: "Only the runway surface itself." },
      { label: "C", text: "Only the terminal building and its facilities." },
      { label: "D", text: "The airspace above an aerodrome up to circuit altitude." },
    ],
    correctAnswer: "A",
    explanation:
      "A defined area intended wholly or partly for aircraft arrival, departure, and surface movement.",
    incorrectAnswerExplanations: {
      B: "Not correct: Only the runway surface itself.",
      C: "Not correct: Only the terminal building and its facilities.",
      D: "Not correct: The airspace above an aerodrome up to circuit altitude.",
    },
    regulationReference:
      "Regulation (EU) No 139/2014, Annexes III and IV; applicable Certification Specifications for Aerodromes",
    difficulty: "intermediate",
    sourceTitle: "EASA Easy Access Rules for Aerodromes",
    sourceUrl: "https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-aerodromes",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
  {
    questionId: "EASA-ATPLA-AL-000231",
    authority: "EASA",
    licence: "ATPL(A)",
    subject: "Air Law",
    chapterTitle: "Aviation Security",
    learningObjective: "Aviation Security",
    questionType: "single_choice",
    questionText: "What is the primary objective of civil aviation security?",
    choices: [
      { label: "A", text: "To maximise airport revenue." },
      { label: "B", text: "To safeguard civil aviation against acts of unlawful interference." },
      { label: "C", text: "To minimise aircraft noise near residential areas." },
      { label: "D", text: "To coordinate customs and immigration procedures." },
    ],
    correctAnswer: "B",
    explanation: "To safeguard civil aviation against acts of unlawful interference.",
    incorrectAnswerExplanations: {
      A: "Not correct: To maximise airport revenue.",
      C: "Not correct: To minimise aircraft noise near residential areas.",
      D: "Not correct: To coordinate customs and immigration procedures.",
    },
    regulationReference: "Regulation (EC) No 300/2008 and Commission Implementing Regulation (EU) 2015/1998, as amended",
    difficulty: "intermediate",
    sourceTitle: "EU common rules in the field of civil aviation security",
    sourceUrl: "https://eur-lex.europa.eu/eli/reg/2008/300/oj",
    lastVerified: "2026-09-11",
    requiresImage: false,
    requiresScratchpad: false,
  },
];
